name: Tests

on:
  push:
  pull_request:

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install

      - name: Tests
        run: vendor/bin/phpunit
